#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#print("This package include:")
#print("The original sequence generated by GaussView 6.0.16")
#print("The correspond sequence according to the representation in Pymol")
#print("The specific sequence according to the existing PDB file")